name: Compilar Flutter (APK e AAB)

on:
  workflow_dispatch:

jobs:
  build:
    name: Configurar Ambiente e Gerar Builds
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: false

      - name: Decodificar Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/horizonte-key.jks

      - name: Criar key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../horizonte-key.jks" >> android/key.properties

      - name: Instalar Dependências
        run: |
          flutter clean
          flutter pub get

      - name: Rodar Testes Automatizados
        run: flutter test

      - name: Gerar Ícones
        run: flutter pub run flutter_launcher_icons

      - name: Compilar APK e AAB Release
        run: |
          flutter build apk --release --dart-define=ONESIGNAL_REST_API_KEY=${{ secrets.ONESIGNAL_REST_API_KEY }}
          flutter build appbundle --release --dart-define=ONESIGNAL_REST_API_KEY=${{ secrets.ONESIGNAL_REST_API_KEY }}

      - name: Renomear Arquivos
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Horizonte-News.apk
          mv build/app/outputs/bundle/release/app-release.aab build/app/outputs/bundle/release/Horizonte-News.aab

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Horizonte-News-APK
          path: build/app/outputs/flutter-apk/Horizonte-News.apk
          retention-days: 7

      - name: Disponibilizar AAB para Download
        uses: actions/upload-artifact@v4
        with:
          name: Horizonte-News-AAB
          path: build/app/outputs/bundle/release/Horizonte-News.aab
          retention-days: 7