Name: Compilar Flutter APK

on:
  workflow_dispatch:

jobs:
  build:
    name: Configurar Ambiente e Gerar APK
    runs-on: ubuntu-latest

    steps:
      - name: Baixar Código do Repositório
        uses: actions/checkout@v4

      - name: Configurar Java JDK (Temurin 17)
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Configurar Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.x'
          channel: 'stable'
          cache: false

      - name: Limpar cache do Gradle
        run: |
          rm -rf ~/.gradle/caches
          rm -rf ~/.gradle/wrapper/dists

      - name: Decodificar Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 --decode > android/horizonte-key.jks

      - name: Criar key.properties
        run: |
          echo "storePassword=${{ secrets.KEYSTORE_PASSWORD }}" > android/key.properties
          echo "keyPassword=${{ secrets.KEY_PASSWORD }}" >> android/key.properties
          echo "keyAlias=${{ secrets.KEY_ALIAS }}" >> android/key.properties
          echo "storeFile=../horizonte-key.jks" >> android/key.properties

      - name: Limpeza, Dependências e Ícones
        run: |
          flutter clean
          flutter pub get
          dart pub global activate flutter_launcher_icons
          dart run flutter_launcher_icons

      - name: Compilar APK Release Universal
        run: flutter build apk --release

      - name: Renomear APK
        run: |
          mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/Horizonte-News.apk

      - name: Disponibilizar APK para Download
        uses: actions/upload-artifact@v4
        with:
          name: Horizonte-News-APK
          path: build/app/outputs/flutter-apk/Horizonte-News.apk
          retention-days: 7
